### ISSUE TITLE
feat: better cross-platform start script 

### ISSUE THREAD

**Issue by erhant** [firstbatchxyz/dkn-compute-node#110]
- [x] Required envs are asked in CLI and an `.env` is created at the active directory
- [x] Admin public key should be set within the code, but can be edited via command line arg if required
- [ ] ~Checks that Docker is up at the start~
- [ ] ~A separate release with the tag `vX.X.X-launch` will be kept, and people will be able to download releases from there.~

**Comment by selimseker** [comment]
We moved the launcher to a seperate [repo](https://github.com/firstbatchxyz/dkn-compute-launcher)
