### ISSUE TITLE
bug: Startsh allow empty RLN_PASSWORD and fix docker-compose command

### ISSUE THREAD

**Issue by erhant** [firstbatchxyz/dkn-compute-node#55]
- It should allow empty string for `RLN_PASSWORD`
- Instead of `docker-compose` we need `docker compose`

**Comment by fco-fbatch** [comment]
You can check [here](https://github.com/firstbatchxyz/hollowdb-backend/blob/e25990c3a5b509cfc6b557512aa611c80332ae2e/compose/compose.sh#L16) to get some inspiration

**Comment by erhant** [comment]
Lets merge the fix into #51 branch

**Comment by erhant** [comment]
Closed with #65
