### ISSUE TITLE
bug: Cancellation for Workflows

### ISSUE THREAD

**Issue by erhant** [firstbatchxyz/dkn-compute-node#72]
Outer wait-for-termination does not work when we are within that `select!`.

**Comment by andthattoo** [comment]
is this for @caglacelik ?

**Comment by erhant** [comment]
yea I think she can look into it, there is a cancellation check at https://github.com/firstbatchxyz/dkn-compute-node/blob/master/src/handlers/workflow.rs#L57 but it doesnt seem to work

maybe we can also think of adding cancelation to ollama workflows as well?
