### ISSUE TITLE
bug: can't use model which pulled manually

### ISSUE THREAD

**Issue by script-money** [firstbatchxyz/dkn-compute-node#86]
### Problem

I follow the guide, pull model manually, but logs show error below

![](https://media.discordapp.net/attachments/1273248419024212038/1273577262842642442/CleanShot_2024-08-15_at_17.40.462x.jpg?ex=66bf1ec1&is=66bdcd41&hm=a518bed6f517bde6176f2f9c474018b79a2b1eb978fc9f0a6edde6abc8a07aed&=&format=webp&width=3840&height=1282)

### How to Reproduce

follow the notion: https://firstbatch.notion.site/How-to-Run-a-Node-ed2bef2c8eec4dd280286f2e081e51d2

1. git clone https://github.com/firstbatchxyz/dkn-compute-node
2. cd dkn-compute-node
3. cp .env.example .env
4. ollama pull llama3.1:latest
5. modify .env (add private key)
6. ./start.sh -m=llama3.1:latest

### Expected Behaviour

Container run without error, can use llamda 3.1

### Version

v0.1.2

### Additional context

1. Set `OLLAMA_AUTO_PULL=true` and `DKN_MODELS=llama3.1:latest` in .env
2. ollama pull hellord/mxbai-embed-large-v1:f16
3. run `./start.sh` will use Ollama:llama3.1:latest without error

**Comment by erhant** [comment]
hey! we just enabled auto-pull so this wont be a problem, P.S. there was issues using local Ollama vs docker Ollama which may be related, also fixed just now

> follow the notion: https://firstbatch.notion.site/How-to-Run-a-Node-ed2bef2c8eec4dd280286f2e081e51d2
> 
> 1. git clone https://github.com/firstbatchxyz/dkn-compute-node
> 2. cd dkn-compute-node
> 3. cp .env.example .env
> 4. ollama pull llama3.1:latest
> 5. modify .env (add private key)
> 6. ./start.sh -m=llama3.1:latest

here right between steps 4 and 5 we needed to do `ollama pull hellord/mxbai-embed-large-v1:f16` as well

would you like to try again with the latest updates? then I can close this one

**Comment by erhant** [comment]
closing the issue, auto-pull solves this nevertheless
